spring:
  datasource:
    driverClassName: org.postgresql.Driver

  jpa:
    generate-ddl: true
    show-sql: true

  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true

springdoc:
  default-produces-media-type: application/json
  show-login-endpoint: true

info:
  app:
    version: '@project.version@'